gmr_dof_names:
  - rw_shoulder_pitch
  - rw_arm_roll
  - rw_forearm_yaw
  
  - lw_shoulder_pitch
  - lw_arm_roll
  - lw_forearm_yaw

  - w_waist_yaw

  - rw_hip_pitch
  - rw_hip_roll
  - rw_hip_yaw
  - rw_knee_pitch
  - rw_foot_pitch
  - rw_foot_roll

  - lrw_hip_pitch
  - lrw_hip_roll
  - lrw_hip_yaw
  - lrw_knee_pitch
  - lrw_foot_pitch
  - lrw_foot_roll


lab_dof_names:
  - lw_shoulder_pitch
  - rw_shoulder_pitch
  - w_waist_yaw
  - lw_arm_roll
  - rw_arm_roll
  - lrw_hip_pitch
  - rw_hip_pitch
  - lw_forearm_yaw
  - rw_forearm_yaw
  - lrw_hip_roll
  - rw_hip_roll
  - lrw_hip_yaw
  - rw_hip_yaw
  - lrw_knee_pitch
  - rw_knee_pitch
  - lrw_foot_pitch
  - rw_foot_pitch
  - lrw_foot_roll
  - rw_foot_roll


# Names of the key bodies that will be used in further processing
# Must match the names in the lab robot model
# Order matters and should align with that used in observation
lab_key_body_names:
  - lrp_foot_roll
  - rp_foot_roll
  
  - lp_forearm_yaw
  - rp_forearm_yaw
  
  - lp_arm_roll
  - rp_arm_roll


# Legged Lab joint names:
# - lw_shoulder_pitch
# - rw_shoulder_pitch
# - w_waist_yaw
# - lw_arm_roll
# - rw_arm_roll
# - lrw_hip_pitch
# - rw_hip_pitch
# - lw_forearm_yaw
# - rw_forearm_yaw
# - lrw_hip_roll
# - rw_hip_roll
# - lrw_hip_yaw
# - rw_hip_yaw
# - lrw_knee_pitch
# - rw_knee_pitch
# - lrw_foot_pitch
# - rw_foot_pitch
# - lrw_foot_roll
# - rw_foot_roll
# Body: base_link, Mass: 1.3998010158538818 kg
# Body: lp_shoulder_pitch, Mass: 0.20385323464870453 kg
# Body: rp_shoulder_pitch, Mass: 0.20385323464870453 kg
# Body: p_waist_yaw, Mass: 0.8242155313491821 kg
# Body: lp_arm_roll, Mass: 0.10494904965162277 kg
# Body: rp_arm_roll, Mass: 0.10494904965162277 kg
# Body: lrp_hip_pitch, Mass: 0.272022545337677 kg
# Body: rp_hip_pitch, Mass: 0.272022545337677 kg
# Body: lp_forearm_yaw, Mass: 0.05490673705935478 kg
# Body: rp_forearm_yaw, Mass: 0.05490673705935478 kg
# Body: lrp_hip_roll, Mass: 0.2306046038866043 kg
# Body: rp_hip_roll, Mass: 0.2306046038866043 kg
# Body: lrp_hip_yaw, Mass: 0.33699727058410645 kg
# Body: rp_hip_yaw, Mass: 0.33699727058410645 kg
# Body: lrp_knee_pitch, Mass: 0.8535988926887512 kg
# Body: rp_knee_pitch, Mass: 0.8535988926887512 kg
# Body: lrp_foot_pitch, Mass: 0.08400003612041473 kg
# Body: rp_foot_pitch, Mass: 0.08400003612041473 kg
# Body: lrp_foot_roll, Mass: 0.14827443659305573 kg
# Body: rp_foot_roll, Mass: 0.14827443659305573 kg

